# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lanace 개발블로그
email: lanace93@gmail.com
description: > # 평소에 공부하고 있는것들을 기록으로 남기기 위해 만들었습니다. 부족한 부분도 많으니 잘 부탁드립니다.
url: "https://lanace.github.io/" # the base hostname & protocol for your site
twitter_username: lanace
github_username:  lanace

# Build settings
markdown: kramdown
